from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil

from agent_spice.backend.base import BackendResult, ProcessBackend


@dataclass(frozen=True)
class NgspiceBackend(ProcessBackend):
    executable: str = "ngspice"
    code_models: tuple[Path, ...] = ()

    def command_for(self, deck_path: Path) -> list[str]:
        return [self.executable, "-b", str(deck_path)]

    def run(self, deck_path: Path, cwd: Path | None = None) -> BackendResult:
        if not self.code_models:
            return super().run(deck_path, cwd=cwd)
        if cwd is None:
            raise ValueError("cwd is required when loading ngspice code models")

        scripts = cwd.resolve() / ".ngspice-scripts"
        staged_models = cwd.resolve() / ".ngspice-code-models"
        scripts.mkdir(parents=True, exist_ok=True)
        staged_models.mkdir(parents=True, exist_ok=True)
        lines = [
            "* Generated by Agent-Spice; isolated from the machine-wide spinit.",
            "alias exit quit",
            "set filetype=ascii",
            "set num_threads=1",
            "unset osdi_enabled",
            "if $?xspice_enabled",
        ]
        for index, model in enumerate(self.code_models):
            resolved = model.resolve()
            if not resolved.is_file():
                raise FileNotFoundError(f"ngspice code model does not exist: {resolved}")
            staged = staged_models / f"{index:03d}-{resolved.name}"
            shutil.copyfile(resolved, staged)
            staged_path = staged.resolve().as_posix()
            if any(character.isspace() for character in staged_path):
                raise ValueError(
                    "ngspice codemodel paths cannot contain whitespace; choose an output root without spaces"
                )
            lines.append(f" codemodel {staged_path}")
        lines.extend(("end", ""))
        (scripts / "spinit").write_text("\n".join(lines), encoding="ascii")
        return super().run(
            deck_path,
            cwd=cwd,
            environment={"SPICE_SCRIPTS": str(scripts)},
        )
